const cards = [
  ['Action (set A)', 'Action (set B)', 'Animal (set A)', 'Animal (set B)', 'Clothes', 'Emotions',
    'Food', 'Drinks'],
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: 'assets/img/cards/cry.jpg',
      audioSrc: 'assets/audio/cards/cry.mp3',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: 'assets/img/cards/dance.jpg',
      audioSrc: 'assets/audio/cards/dance.mp3',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: 'assets/img/cards/dive.jpg',
      audioSrc: 'assets/audio/cards/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: 'assets/img/cards/draw.jpg',
      audioSrc: 'assets/audio/cards/draw.mp3',
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'assets/img/cards/fish.jpg',
      audioSrc: 'assets/audio/cards/fish.mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: 'assets/img/cards/fly.jpg',
      audioSrc: 'assets/audio/cards/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: 'assets/img/cards/hug.jpg',
      audioSrc: 'assets/audio/cards/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: 'assets/img/cards/jump.jpg',
      audioSrc: 'assets/audio/cards/jump.mp3',
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      image: 'assets/img/cards/open.jpg',
      audioSrc: 'assets/audio/cards/open.mp3',
    },
    {
      word: 'play',
      translation: 'играть',
      image: 'assets/img/cards/play.jpg',
      audioSrc: 'assets/audio/cards/play.mp3',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: 'assets/img/cards/point.jpg',
      audioSrc: 'assets/audio/cards/point.mp3',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: 'assets/img/cards/ride.jpg',
      audioSrc: 'assets/audio/cards/ride.mp3',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: 'assets/img/cards/run.jpg',
      audioSrc: 'assets/audio/cards/run.mp3',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: 'assets/img/cards/sing.jpg',
      audioSrc: 'assets/audio/cards/sing.mp3',
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: 'assets/img/cards/skip.jpg',
      audioSrc: 'assets/audio/cards/skip.mp3',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: 'assets/img/cards/swim.jpg',
      audioSrc: 'assets/audio/cards/swim.mp3',
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: 'assets/img/cards/cat.jpg',
      audioSrc: 'assets/audio/cards/cat.mp3',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: 'assets/img/cards/chick.jpg',
      audioSrc: 'assets/audio/cards/chick.mp3',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'assets/img/cards/chicken.jpg',
      audioSrc: 'assets/audio/cards/chicken.mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'assets/img/cards/dog.jpg',
      audioSrc: 'assets/audio/cards/dog.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: 'assets/img/cards/horse.jpg',
      audioSrc: 'assets/audio/cards/horse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'assets/img/cards/pig.jpg',
      audioSrc: 'assets/audio/cards/pig.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: 'assets/img/cards/rabbit.jpg',
      audioSrc: 'assets/audio/cards/rabbit.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: 'assets/img/cards/sheep.jpg',
      audioSrc: 'assets/audio/cards/sheep.mp3',
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: 'assets/img/cards/bird.jpg',
      audioSrc: 'assets/audio/cards/bird.mp3',
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: 'assets/img/cards/fish1.jpg',
      audioSrc: 'assets/audio/cards/fish.mp3',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: 'assets/img/cards/frog.jpg',
      audioSrc: 'assets/audio/cards/frog.mp3',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: 'assets/img/cards/giraffe.jpg',
      audioSrc: 'assets/audio/cards/giraffe.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'assets/img/cards/lion.jpg',
      audioSrc: 'assets/audio/cards/lion.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'assets/img/cards/mouse.jpg',
      audioSrc: 'assets/audio/cards/mouse.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'assets/img/cards/turtle.jpg',
      audioSrc: 'assets/audio/cards/turtle.mp3',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'assets/img/cards/dolphin.jpg',
      audioSrc: 'assets/audio/cards/dolphin.mp3',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'assets/img/cards/skirt.jpg',
      audioSrc: 'assets/audio/cards/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'assets/img/cards/pants.jpg',
      audioSrc: 'assets/audio/cards/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'assets/img/cards/blouse.jpg',
      audioSrc: 'assets/audio/cards/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'assets/img/cards/dress.jpg',
      audioSrc: 'assets/audio/cards/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'assets/img/cards/boot.jpg',
      audioSrc: 'assets/audio/cards/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'assets/img/cards/shirt.jpg',
      audioSrc: 'assets/audio/cards/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'assets/img/cards/coat.jpg',
      audioSrc: 'assets/audio/cards/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: 'assets/img/cards/shoe.jpg',
      audioSrc: 'assets/audio/cards/shoe.mp3',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: 'assets/img/cards/sad.jpg',
      audioSrc: 'assets/audio/cards/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'assets/img/cards/angry.jpg',
      audioSrc: 'assets/audio/cards/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'assets/img/cards/happy.jpg',
      audioSrc: 'assets/audio/cards/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: 'assets/img/cards/tired.jpg',
      audioSrc: 'assets/audio/cards/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'assets/img/cards/surprised.jpg',
      audioSrc: 'assets/audio/cards/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: 'assets/img/cards/scared.jpg',
      audioSrc: 'assets/audio/cards/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: 'assets/img/cards/smile.jpg',
      audioSrc: 'assets/audio/cards/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: 'assets/img/cards/laugh.jpg',
      audioSrc: 'assets/audio/cards/laugh.mp3',
    },
  ],
  [
    {
      word: 'banana',
      translation: 'банан',
      image: 'assets/img/cards/banana.jpg',
      audioSrc: 'assets/audio/cards/banana.mp3',
    },
    {
      word: 'apple',
      translation: 'яблоко',
      image: 'assets/img/cards/apple.jpg',
      audioSrc: 'assets/audio/cards/apple.mp3',
    },
    {
      word: 'meat',
      translation: 'мясо',
      image: 'assets/img/cards/meat.jpg',
      audioSrc: 'assets/audio/cards/meat.mp3',
    },
    {
      word: 'mushroom',
      translation: 'гриб',
      image: 'assets/img/cards/mushroom.jpg',
      audioSrc: 'assets/audio/cards/mushroom.mp3',
    },
    {
      word: 'orange',
      translation: 'апельсин',
      image: 'assets/img/cards/orange.jpg',
      audioSrc: 'assets/audio/cards/orange.mp3',
    },
    {
      word: 'bread',
      translation: 'хлеб',
      image: 'assets/img/cards/bread.jpg',
      audioSrc: 'assets/audio/cards/bread.mp3',
    },
    {
      word: 'sweet',
      translation: 'конфета',
      image: 'assets/img/cards/sweet.jpg',
      audioSrc: 'assets/audio/cards/sweet.mp3',
    },
    {
      word: 'cake',
      translation: 'торт',
      image: 'assets/img/cards/cake.jpg',
      audioSrc: 'assets/audio/cards/cake.mp3',
    },
  ],
  [
    {
      word: 'cocoa',
      translation: 'какао',
      image: 'assets/img/cards/cocoa.jpg',
      audioSrc: 'assets/audio/cards/cocoa.mp3',
    },
    {
      word: 'coffee',
      translation: 'кофе',
      image: 'assets/img/cards/coffee.jpg',
      audioSrc: 'assets/audio/cards/coffee.mp3',
    },
    {
      word: 'juice',
      translation: 'сок',
      image: 'assets/img/cards/juice.jpg',
      audioSrc: 'assets/audio/cards/juice.mp3',
    },
    {
      word: 'compote',
      translation: 'компот',
      image: 'assets/img/cards/compote.jpg',
      audioSrc: 'assets/audio/cards/compote.mp3',
    },
    {
      word: 'milk',
      translation: 'молоко',
      image: 'assets/img/cards/milk.jpg',
      audioSrc: 'assets/audio/cards/milk.mp3',
    },
    {
      word: 'tea',
      translation: 'чай',
      image: 'assets/img/cards/tea.jpg',
      audioSrc: 'assets/audio/cards/tea.mp3',
    },
    {
      word: 'water',
      translation: 'вода',
      image: 'assets/img/cards/water.jpg',
      audioSrc: 'assets/audio/cards/water.mp3',
    },
    {
      word: 'soda',
      translation: 'газировка',
      image: 'assets/img/cards/soda.jpg',
      audioSrc: 'assets/audio/cards/soda.mp3',
    },
  ],
];

export default cards;
